[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd voyage_backend && npm ci']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd voyage_backend && node server.js'

